// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    return $(".boxgrid.captionfull").hover((function() {
      return $(".cover", this).stop().animate({
        top: "160px"
      }, {
        queue: false,
        duration: 160
      });
    }), function() {
      return $(".cover", this).stop().animate({
        top: "260px"
      }, {
        queue: false,
        duration: 160
      });
    });
  });

}).call(this);
